### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [cnlohr/epaper_projects#1]
Hello!

I found link to this project from https://hackaday.com/2020/10/30/color-e-ink-display-photo-frame-pranks-mom/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by vazhnov** [comment]
@cnlohr ?

**Comment by cnlohr** [comment]
Hey, sorry about that.  Yes.  It's all public, MIT/X11 or NewBSD licenses (unless content is owned by someone else)

**Comment by cnlohr** [comment]
(It has been resolved)

**Comment by vazhnov** [comment]
@cnlohr , great, thank you!
